### ISSUE TITLE
Timestamp Builder API Mismatch

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#190]
The [code][1] in the builder that builds a `Timestamp` seems to contradict the `build_at_offset` builder API [here][2]:

```rust
    pub fn build_at_offset(mut self, offset_minutes: i32) -> IonResult<Timestamp> {
        self.builder.offset = Some(offset_minutes);
        self.into_builder().build()
    }
```

The parameter above is minutes, but the corresponding code that builds the `FixedOffset`:

```rust
            let offset = FixedOffset::west_opt(offset).ok_or_else(|| {
                illegal_operation_raw(format!("specified offset ('{}') is invalid", offset))
            })?;
```

So for the `UTC-08:00` offset, one would need to pass `28800` to the `build_at_offset` which doesn't seem right since the parameter indicates minutes.  My expectation would be that `-480` would be the argument--at a minimum we should be clarifying what this parameter means.

[1]: https://github.com/amzn/ion-rust/blob/1347af2b31fd43b0b6adff99a15c693ab75d1253/src/types/timestamp.rs#L337-L340
[2]: https://github.com/amzn/ion-rust/blob/1347af2b31fd43b0b6adff99a15c693ab75d1253/src/types/timestamp.rs#L470-L473

**Comment by zslayton** [comment]
As discussed offline, this was indeed a mistake. I started writing the API with `minutes` (as are used in the Ion spec) and then drifted into using `seconds` because that's what `chron::FixedOffset` used. I also meant to use `east_opt` rather than `west_opt` so that timezones in the western hemisphere would take a negative number of minutes.
