### ISSUE TITLE
Re-export Dependencies for Public APIs

### ISSUE THREAD

**Issue by almann** [amzn/ion-rust#302]
As indicated on [this issue][1], we should be not exporting data types in our public APIs of our dependencies.  This will allow for multiple versions of a dependency to more easily co-exist in down stream dependents.

For example, instead of directly returning `bigdecimal::BigDecimal` in our APIs, we should return something like `ion_rs::bigdecimal::BigDecimal` which in our `lib.rs`, might look something like:

```rust
pub use bigdecimal;
```

We may want to put these re-exports in a sub-module to emphasize that we are just re-exporting them, but other candidates for this are `chrono`, `num-bigint`, `num-traits`, and even `ion-c-sys` when such types are part of our public API.

Note that this would require us to actually change any of the APIs that use these types to use the re-exported ones instead, but that should be a fairly mechanical change.

[1]: https://github.com/awslabs/amazon-qldb-shell/pull/135#issuecomment-908631701

**Comment by marcbowes** [comment]
Bikeshed: do you think `ion_rs::bigdecimal::BigDecimal` or .. `ion_rs::types::bigdecimal::BigDecimal`, such that it's a sibling of `types::Decimal`?

**Comment by almann** [comment]
I had a slight preference towards putting them in a sub-module like `ext` or something to make it clear that these were coming from other crates.  E.g. `ion_rs::ext::bigdecimal::BigDecimal`.

**Comment by marcbowes** [comment]
I think `ext` is probably not what we want, since it's common to have `FooExt` trait naming to show extensions to the base foo type.

I'm good with a reexport module somewhere, but I'm not sure whether it should be at the top level or under types..

1. `ion_rs::reexport::bigdecimal::BigDecimal`
2. `ion_rs::types::reexport::bigdecimal::BigDecimal`

I'm inclined to 1, even though 2 makes a bit more organizational sense.
