### ISSUE TITLE
Integration with serde

### ISSUE THREAD

**Issue by fimbault** [amzn/ion-rust#89]
would be cool ;-)

**Comment by b41sh** [comment]
Do we have plans to implement trait `serde::Serialize` and `serde::Deserialize` for `OwnedElement`? @desaikd @zslayton

**Comment by zslayton** [comment]
Hi @b41sh. Unfortunately, [serde's data model](https://serde.rs/data-model.html) is too limited to read and write Ion without data loss. I've tried to writing an implementation of this but there's no way to work with timestamps, decimals, or annotations. 

As an example: if a deserializer encountered a `timestamp` in an Ion stream, it would have to map it to one of Serde's types. Because Serde doesn't have a `datetime`/`instant`/`timestamp` type to map to, we would [have to shoehorn that value into a `String`](https://serde.rs/custom-date-format.html) or return it as an `i64` value containing an epoch time. Both approaches defeat the purpose of using a serialization format with strong typing; the application would need to jump through hoops to get that `String` or `i64` back into type that's unambiguously a representation of a point in time.

Annotations and decimal values run into a similar problem; there's not a way to represent them in the Serde type system, so we'd have to convert them into an improvised representation or use `unsafe` tricks to bypass the type system altogether. This is known as "[in-band signaling](https://github.com/serde-rs/serde/issues/1463)"; while it can work for a single application, it breaks compatibility between `serde` implementations. (e.g. you can no longer [transcode between formats](https://serde.rs/transcode.html) without collecting the input into an intermediate form.) Even a second Ion `serde` implementation would be incompatible with the first.

This problem is not unique to Ion; the CBOR implementation [ran into similar problems trying to implement support for tags](https://github.com/serde-rs/serde/pull/1643) (which are analogous to Ion's annotations).

This was the developer's [reply to the PR](https://github.com/serde-rs/serde/pull/1643#pullrequestreview-307593006):

> Thanks for the PR! I think unfortunately introducing support for tagged values wouldn't be the right course for Serde. It isn't a goal for the data model to be a union of all the features of data formats that people care about. Rather it's a fairly selective subset that translates well across a range of formats (and maybe would be smaller if it were being redesigned today). Formats that equate naturally with the data model are a good fit for Serde. Formats where a subset can be made to fit the data model (like serde_cbor today) are still often useful for working within that subset. Beyond that, I would recommend building dedicated libraries to get full coverage of individual formats -- such as I've encouraged in the past for formats that care about element types of empty lists and maps, formats that care about preserving comments or whitespace, formats that distinguish between fields and attributes, etc.

At the moment our inclination is to eventually provide an `derive`-style interface that works similarly to serde but which can support Ion's complete type system. This is a non-trivial undertaking and won't be worked on until the foundation of the library is complete. If anyone would like to make the case for a `serde` implementation that only supports JSON-ish types or which uses in-band signaling (breaking some contractual obligations), they're welcome to!

**Comment by b41sh** [comment]
I see, thanks for your timely reply and explanation. @zslayton
